const players=[
    { id : "01",
      FullName: "Cristiano Ronaldo dos Santos Aveiro",
     Age : 39,
     Team : "Real Madrid",
     Nationality: "Portugaise",
     JerseyNumber : 7,
      ImageUrl : "https://upload.wikimedia.org/wikipedia/commons/d/d7/Cristiano_Ronaldo_playing_for_Al_Nassr_FC_against_Persepolis%2C_September_2023_(cropped).jpg"
    },{id : "02",
    FullName: "Toni Kroos",
    Age : 34,
    Team : "Bayern Munich",
    Nationality: "Allemagne",
    JerseyNumber : 8,
     ImageUrl : "https://upload.wikimedia.org/wikipedia/commons/9/98/CSKA-RM18_(7)_(cropped).jpg"},
     {id : "03",
     FullName: "Kylian Mbappé",
     Age : 25,
     Team : "Paris Saint-Germain",
     Nationality: "Française",
     JerseyNumber : 7,
      ImageUrl : "https://upload.wikimedia.org/wikipedia/commons/b/b3/2022_FIFA_World_Cup_France_4–1_Australia_-_(7)_(cropped).jpg"},
     {id : "04",
     FullName: "Erling Haaland",
     Age : 23,
     Team : "Manchester City",
     Nationality: "Britanique,Norvégienne",
     JerseyNumber : 9,
      ImageUrl : "https://upload.wikimedia.org/wikipedia/commons/0/07/Erling_Haaland_2023_(cropped).jpg"},
     {id : "05",
     FullName: "Jude Bellingham",
     Age : 20,
     Team : "Real Madrid",
     Nationality: "Britanique,Irlandaise",
     JerseyNumber : 5,
      ImageUrl : "https://upload.wikimedia.org/wikipedia/commons/f/f4/25th_Laureus_World_Sports_Awards_-_240422_205212_(cropped).jpg"}
]

export default players
